@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=api
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

// AUTHENTICATION ROUTES
### Register new user
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "monusername",
    "email": "monemail1@monemail.fr",
    "password": "monpassword",
    "avatar": 1
  }
### Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "nicolas@oak.fr",
    "password": "monpassword"
  }

// AUTHOR ROUTES
### Get all authors
GET {{baseUrl}}/authors
### Get author by id
GET {{baseUrl}}/author/1

/// BADGE ROUTES
### Get all badges
GET {{baseUrl}}/badges
### Get badge by id
GET {{baseUrl}}/badge/1

// BOOK ROUTES
### Get all books
GET {{baseUrl}}/books
### Get book by id
GET {{baseUrl}}/book/2
### Delete book by id
DELETE {{baseUrl}}/book/2
### Add book to list
POST {{baseUrl}}/book
Content-Type: application/json

{
  "title" : "T'choupi fait du vélo",
  "user_id" : 1,
  "public_api_id":"Dw-3HAAACAAJ",
  "list_id":1
  }


// BOOKPOSITION ROUTES
### Get all bookPositions
GET {{baseUrl}}/bookPositions
### Get bookPosition by id
GET {{baseUrl}}/bookPosition/1


// LIST ROUTES
### Get all lists
GET {{baseUrl}}/lists
### Get list by id
GET {{baseUrl}}/list/23
### Get lists by UserId
GET {{baseUrl}}/lists/user/1
### Delete list by id
DELETE {{baseUrl}}/list/25
### Add List
POST {{baseUrl}}/list
Content-Type: application/json

{
    "label": "Label de ma liste",
    "position": 3,
    "description": "Description de ma liste",
    "user_id": 1
  }
### Update list by id
PATCH {{baseUrl}}/list/24
Content-Type: application/json

{
    "id": 24,
    "label": "Label de ma liste",
    "position": 3,
    "description": "Description de ma liste",
    "user_id": 1
}


// RATING ROUTES
### Get all ratings
GET {{baseUrl}}/ratings
### Get rating by id
GET {{baseUrl}}/rating/1


// REVIEW ROUTES
### Get all reviews
GET {{baseUrl}}/reviews
### Get review by id
GET {{baseUrl}}/review/1


// ROLE ROUTES
### Get all roles
GET {{baseUrl}}/roles
### Get role by id
GET {{baseUrl}}/role/1


// USER ROUTES
### Get all users
GET {{baseUrl}}/users
### Get user by id
GET {{baseUrl}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoibW9udXNlcm5hbWUiLCJlbWFpbCI6Im1vbmVtYWlsQG1vbmVtYWlsLmZyIiwiYXZhdGFyIjoxLCJyb2xlX2lkIjoyLCJpYXQiOjE2MTUyMTkyMDB9.1-rwc3XG_-m0h2x-3DmeEpOpIDso0KWXsP8vxihezdo